name: Container
on: pull_request

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:13.5.0-alpine3.10
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
  node-docker-local-code-service:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Post a user
        run: 'curl -X POST http://localhost:3001/api/user -H
         ''Content-Type: application/json'' -d ''{"username": "hi", "address": "abc"}'''
      - name: Get Users
        run: curl http://localhost:3001/api/users