name: Matrix
on: push

jobs:
  node-version:
    runs-on: ubuntu-22.04
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: Log node version
        run: node -v
  different-version:
    runs-on: ubuntu-18.04
    steps:
      - name: Another node version
        run: node -v
  node-version-with-matrix-strategy:
    strategy:
      matrix:
        node_version: [6, 8, 10]
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            node_version: 10
            is_ubuntu_10: "true"
        exclude:
          - os: macos-latest
            node_version: 8
          - os: windows-latest
            node_version: 6
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_10: ${{ matrix.is_ubuntu_10 }}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log node version
        run: |
          node -v
          echo $IS_UBUNTU_10